// p9azpg-movie-watchlist/repository_after/src/routes/search/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { getPosterUrl } from '$lib/api/tmdb';
	import type { TMDBMovie } from '$lib/api/tmdb';

	let query = $state('');
	let results: TMDBMovie[] = $state([]);
	let loading = $state(false);
	let error = $state('');

	async function handleSearch() {
		if (!query.trim()) return;

		loading = true;
		error = '';

		try {
			const response = await fetch(`/api/movies/search?q=${encodeURIComponent(query)}`);
			if (!response.ok) throw new Error('Search failed');

			const data = await response.json();
			results = data.results;
		} catch (err) {
			error = 'Failed to search movies';
		} finally {
			loading = false;
		}
	}

	function handleKeyPress(e: KeyboardEvent) {
		if (e.key === 'Enter') {
			handleSearch();
		}
	}
</script>

<svelte:head>
	<title>Search Movies - CineTrack</title>
</svelte:head>

<div class="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
	<div class="animate-fade-in mb-8">
		<h1 class="font-display text-gradient mb-2 text-4xl font-bold">Discover Movies</h1>
		<p class="text-gray-400">Search for movies to add to your watchlist</p>
	</div>

	<!-- Search Bar -->
	<div class="animate-fade-in mb-8" style="animation-delay: 0.1s;">
		<div class="flex gap-3">
			<input
				type="text"
				bind:value={query}
				onkeypress={handleKeyPress}
				placeholder="Search for movies..."
				class="input-field flex-1"
			/>
			<button onclick={handleSearch} disabled={loading} class="btn-primary disabled:opacity-50">
				{loading ? 'Searching...' : 'Search'}
			</button>
		</div>
	</div>

	{#if error}
		<div class="mb-6 rounded-lg border border-red-500/50 bg-red-500/10 p-4 text-red-400">
			{error}
		</div>
	{/if}

	{#if results.length > 0}
		<div class="animate-fade-in" style="animation-delay: 0.2s;">
			<p class="mb-4 text-gray-400">Found {results.length} results</p>

			<div class="grid grid-cols-2 gap-4 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5">
				{#each results as movie}
					<a href="/movie/{movie.id}" class="card group cursor-pointer">
						<div class="aspect-[2/3] overflow-hidden">
							<img
								src={getPosterUrl(movie.poster_path)}
								alt={movie.title}
								class="h-full w-full object-cover transition-transform duration-300 group-hover:scale-110"
							/>
						</div>
						<div class="p-3">
							<h3 class="mb-1 line-clamp-2 text-sm font-semibold">{movie.title}</h3>
							<div class="flex items-center justify-between text-xs">
								<span class="text-gray-400">{movie.release_date?.substring(0, 4) || 'N/A'}</span>
								<span class="text-cinema-accent">⭐ {movie.vote_average.toFixed(1)}</span>
							</div>
						</div>
					</a>
				{/each}
			</div>
		</div>
	{:else if !loading && query}
		<div class="py-16 text-center text-gray-400">
			No results found for "{query}"
		</div>
	{/if}

	{#if !query && !loading}
		<div class="animate-fade-in py-16 text-center">
			<div class="mb-4 text-6xl">🔍</div>
			<h3 class="font-display mb-2 text-2xl font-bold">Start your search</h3>
			<p class="text-gray-400">Enter a movie title to begin</p>
		</div>
	{/if}
</div>

// 5ritkb-personalized-reading-tracker/repository_after/frontend/src/views/Search.vue
<script setup lang="ts">
import { ref } from 'vue'
import { Search as SearchIcon, Loader2, BookOpen, CheckCircle, Bookmark } from 'lucide-vue-next'
import api from '../services/api'
import BookCover from '../components/BookCover.vue'

const query = ref('')
const results = ref<any[]>([])
const searching = ref(false)

const handleSearch = async () => {
  if (query.value.length < 2) {
    results.value = []
    return
  }
  searching.value = true
  try {
    const response = await api.get(`/books/search?q=${query.value}`)
    results.value = response.data
  } catch (e) {
    console.error("Search API Error:", e)
  } finally {
    searching.value = false
  }
}

const addToShelf = async (book: any, status: string) => {
  try {
    const payload = {
      id: book.id,
      title: book.title,
      author: book.author,
      cover: book.cover,
      pages: book.pages,
      status: status    
    }
    await api.post('/shelf/add', payload)
    alert(`Added "${book.title}" to library!`)
  } catch (e: any) {
    if (e.response?.status === 400) {
      alert("This book is already in your library!")
    }
  }
}
</script>

<template>
  <div class="p-6 max-w-5xl mx-auto">
    <h1 class="text-3xl font-black mb-2 text-slate-800 tracking-tight">Find New Books</h1>
    <p class="text-slate-500 mb-8 font-medium">Search the library and add books to your shelves.</p>
    
    <div class="relative mb-8">
      <SearchIcon class="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" :size="20" />
      <input 
        v-model="query"
        @input="handleSearch"
        type="text" 
        placeholder="Search by title or author..."
        class="w-full pl-12 pr-4 py-4 bg-white rounded-2xl shadow-sm border border-slate-200 outline-none focus:ring-2 focus:ring-indigo-500 transition-all font-medium"
      />
    </div>

    <div v-if="searching" class="flex justify-center py-10">
      <Loader2 class="animate-spin text-indigo-600" :size="40" />
    </div>

    <div v-else class="grid grid-cols-1 md:grid-cols-2 gap-6">
      <div v-for="book in results" :key="book.id" 
           class="bg-white p-4 rounded-3xl shadow-sm border border-slate-100 flex gap-4 hover:shadow-xl transition-all duration-300">
        
        <div class="w-24 h-36 flex-shrink-0">
          <BookCover :src="book.cover" :title="book.title" />
        </div>
        
        <div class="flex-1 flex flex-col justify-between">
          <div>
            <div class="font-black text-lg text-slate-900 leading-tight">{{ book.title }}</div>
            <div class="text-sm font-bold text-slate-400 mt-1 uppercase tracking-wider">{{ book.author }}</div>
          </div>

          <div class="flex flex-wrap gap-2 mt-4">
            <button @click="addToShelf(book, 'want-to-read')" 
                    class="flex items-center gap-1.5 text-xs font-black bg-slate-100 text-slate-700 px-3 py-2 rounded-xl hover:bg-slate-200">
              <Bookmark :size="14" /> Want
            </button>
            <button @click="addToShelf(book, 'currently-reading')" 
                    class="flex items-center gap-1.5 text-xs font-black bg-indigo-50 text-indigo-700 px-3 py-2 rounded-xl hover:bg-indigo-100">
              <BookOpen :size="14" /> Reading
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
