// zuyxhx-time-tracking-app-clock-in-clock-out-reports/repository_after/frontend/pages/register.vue
<template>
  <div class="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
    <div class="max-w-md w-full space-y-8">
      <div>
        <h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900">Create your account</h2>
      </div>
      <form class="mt-8 space-y-6" @submit.prevent="handleRegister">
        <div v-if="error" class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded">
          {{ error }}
        </div>
        <div v-if="success" class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded">
          Registration successful! <NuxtLink to="/login" class="underline">Login here</NuxtLink>
        </div>
        <div class="rounded-md shadow-sm -space-y-px">
          <div>
            <label for="email" class="sr-only">Email address</label>
            <input v-model="email" id="email" name="email" type="email" required
              class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
              placeholder="Email address">
          </div>
          <div>
            <label for="password" class="sr-only">Password</label>
            <input v-model="password" id="password" name="password" type="password" required minlength="6"
              class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
              placeholder="Password (min 6 characters)">
          </div>
          <div>
            <label for="confirmPassword" class="sr-only">Confirm Password</label>
            <input v-model="confirmPassword" id="confirmPassword" name="confirmPassword" type="password" required
              class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
              placeholder="Confirm password">
          </div>
        </div>
        <div>
          <button type="submit" :disabled="authStore.loading"
            class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none disabled:opacity-50">
            {{ authStore.loading ? 'Registering...' : 'Register' }}
          </button>
        </div>
        <div class="text-center">
          <NuxtLink to="/login" class="text-indigo-600 hover:text-indigo-500">
            Already have an account? Sign in
          </NuxtLink>
        </div>
      </form>
    </div>
  </div>
</template>

<script setup lang="ts">
const authStore = useAuthStore()

const email = ref('')
const password = ref('')
const confirmPassword = ref('')
const error = ref('')
const success = ref(false)

async function handleRegister() {
  error.value = ''
  success.value = false

  if (password.value !== confirmPassword.value) {
    error.value = 'Passwords do not match'
    return
  }

  if (password.value.length < 6) {
    error.value = 'Password must be at least 6 characters'
    return
  }

  const result = await authStore.register({ email: email.value, password: password.value })
  if (result.success) {
    success.value = true
    email.value = ''
    password.value = ''
    confirmPassword.value = ''
  } else {
    error.value = result.error || 'Registration failed'
  }
}
</script>

// p9azpg-movie-watchlist/repository_after/src/routes/register/+page.svelte
<script lang="ts">
	import { enhance } from '$app/forms';
	import type { ActionData } from './$types';

	let { form }: { form: ActionData } = $props();
	let loading = $state(false);
</script>

<svelte:head>
	<title>Sign Up - CineTrack</title>
</svelte:head>

<div
	class="from-cinema-darker via-cinema-dark to-cinema-blue/20 flex min-h-screen items-center justify-center bg-gradient-to-br px-4 py-12"
>
	<div class="pointer-events-none absolute inset-0 overflow-hidden">
		<div class="bg-cinema-accent/10 absolute top-20 right-10 h-64 w-64 rounded-full blur-3xl"></div>
		<div
			class="bg-cinema-purple/10 absolute bottom-20 left-10 h-96 w-96 rounded-full blur-3xl"
		></div>
	</div>

	<div class="relative z-10 w-full max-w-md">
		<div class="animate-fade-in mb-8 text-center">
			<div class="mb-4 text-6xl">🎬</div>
			<h1 class="font-display text-gradient mb-2 text-5xl font-bold">CineTrack</h1>
			<p class="text-gray-400">Start tracking your movie journey</p>
		</div>

		<div class="card animate-fade-in p-8" style="animation-delay: 0.2s;">
			<h2 class="font-display mb-6 text-center text-2xl font-bold">Create Account</h2>

			{#if form?.error}
				<div
					class="mb-6 rounded-lg border border-red-500/50 bg-red-500/10 p-4 text-sm text-red-400"
				>
					{form.error}
				</div>
			{/if}

			<form
				method="POST"
				use:enhance={() => {
					loading = true;
					return async ({ update }) => {
						await update();
						loading = false;
					};
				}}
			>
				<div class="space-y-4">
					<div>
						<label for="name" class="mb-2 block text-sm font-medium text-gray-300">Name</label>
						<input
							type="text"
							id="name"
							name="name"
							required
							class="input-field"
							placeholder="Your name"
						/>
					</div>

					<div>
						<label for="email" class="mb-2 block text-sm font-medium text-gray-300">Email</label>
						<input
							type="email"
							id="email"
							name="email"
							required
							class="input-field"
							placeholder="your@email.com"
						/>
					</div>

					<div>
						<label for="password" class="mb-2 block text-sm font-medium text-gray-300"
							>Password</label
						>
						<input
							type="password"
							id="password"
							name="password"
							required
							minlength="8"
							class="input-field"
							placeholder="••••••••"
						/>
						<p class="mt-1 text-xs text-gray-500">At least 8 characters</p>
					</div>

					<button
						type="submit"
						disabled={loading}
						class="btn-primary w-full disabled:cursor-not-allowed disabled:opacity-50"
					>
						{loading ? 'Creating account...' : 'Sign Up'}
					</button>
				</div>
			</form>

			<div class="mt-6 text-center text-sm text-gray-400">
				Already have an account?
				<a href="/login" class="text-cinema-pink hover:text-cinema-accent ml-1 font-semibold">
					Login
				</a>
			</div>
		</div>
	</div>
</div>
