// b8sg4e-full-stack-secure-web-application-with-replay-protection/repository_after/frontend/src/app/login/page.tsx
'use client';

import { useState, FormEvent } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { useAuth } from '@/contexts/AuthContext';
import toast from 'react-hot-toast';

export default function LoginPage() {
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [totpToken, setTotpToken] = useState('');
    const [requires2FA, setRequires2FA] = useState(false);
    const [isLoading, setIsLoading] = useState(false);
    const [errors, setErrors] = useState<{ email?: string; password?: string; totp?: string }>({});

    const { login } = useAuth();
    const router = useRouter();

    const validateForm = () => {
        const newErrors: { email?: string; password?: string; totp?: string } = {};

        if (!email) {
            newErrors.email = 'Email is required';
        } else if (!/\S+@\S+\.\S+/.test(email)) {
            newErrors.email = 'Please enter a valid email';
        }

        if (!password) {
            newErrors.password = 'Password is required';
        } else if (password.length < 6) {
            newErrors.password = 'Password must be at least 6 characters';
        }

        if (requires2FA && !totpToken) {
            newErrors.totp = '2FA token is required';
        } else if (requires2FA && !/^\d{6}$/.test(totpToken)) {
            newErrors.totp = 'Enter a valid 6-digit code';
        }

        setErrors(newErrors);
        return Object.keys(newErrors).length === 0;
    };

    const handleSubmit = async (e: FormEvent) => {
        e.preventDefault();

        if (!validateForm()) return;

        setIsLoading(true);

        try {
            const result = await login(email, password, requires2FA ? totpToken : undefined);

            if (result.success) {
                toast.success('Welcome back!');
                router.push('/dashboard');
            } else if (result.requires2FA) {
                setRequires2FA(true);
                toast('Please enter your 2FA code', { icon: '🔐' });
            } else {
                toast.error(result.error || 'Login failed');
            }
        } catch {
            toast.error('An unexpected error occurred');
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <div className="flex items-center justify-center" style={{ minHeight: '100vh', padding: '2rem' }}>
            <div className="card" style={{ width: '100%', maxWidth: '24rem' }}>
                <div className="card-header text-center">
                    <h1 className="page-title" style={{ fontSize: '1.75rem', marginBottom: '0.5rem' }}>
                        Welcome Back
                    </h1>
                    <p className="text-secondary text-sm">
                        Sign in to your secure account
                    </p>
                </div>

                <form onSubmit={handleSubmit} className="card-body">
                    <div className="form-group">
                        <label htmlFor="email" className="form-label">Email Address</label>
                        <input
                            type="email"
                            id="email"
                            className={`form-input ${errors.email ? 'error' : ''}`}
                            placeholder="you@example.com"
                            value={email}
                            onChange={(e) => setEmail(e.target.value)}
                            disabled={isLoading}
                        />
                        {errors.email && <p className="form-error">{errors.email}</p>}
                    </div>

                    <div className="form-group">
                        <label htmlFor="password" className="form-label">Password</label>
                        <input
                            type="password"
                            id="password"
                            className={`form-input ${errors.password ? 'error' : ''}`}
                            placeholder="••••••••"
                            value={password}
                            onChange={(e) => setPassword(e.target.value)}
                            disabled={isLoading}
                        />
                        {errors.password && <p className="form-error">{errors.password}</p>}
                    </div>

                    {requires2FA && (
                        <div className="form-group">
                            <label htmlFor="totpToken" className="form-label">2FA Code</label>
                            <input
                                type="text"
                                id="totpToken"
                                className={`form-input ${errors.totp ? 'error' : ''}`}
                                placeholder="000000"
                                value={totpToken}
                                onChange={(e) => setTotpToken(e.target.value.replace(/\D/g, '').slice(0, 6))}
                                disabled={isLoading}
                                maxLength={6}
                                autoFocus
                            />
                            {errors.totp && <p className="form-error">{errors.totp}</p>}
                            <p className="form-hint">Enter the 6-digit code from your authenticator app</p>
                        </div>
                    )}

                    <button
                        type="submit"
                        className="btn btn-primary w-full"
                        disabled={isLoading}
                        style={{ marginTop: '1rem' }}
                    >
                        {isLoading ? (
                            <>
                                <span className="spinner" />
                                Signing in...
                            </>
                        ) : (
                            'Sign In'
                        )}
                    </button>
                </form>

                <div className="card-footer text-center">
                    <p className="text-sm text-secondary">
                        Don&apos;t have an account?{' '}
                        <Link href="/register" className="font-semibold">
                            Create one
                        </Link>
                    </p>
                </div>
            </div>
        </div>
    );
}

// zuyxhx-time-tracking-app-clock-in-clock-out-reports/repository_after/frontend/pages/login.vue
<template>
  <div class="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
    <div class="max-w-md w-full space-y-8">
      <div>
        <h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900">Sign in to your account</h2>
      </div>
      <form class="mt-8 space-y-6" @submit.prevent="handleLogin">
        <div v-if="error" class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded">
          {{ error }}
        </div>
        <div class="rounded-md shadow-sm -space-y-px">
          <div>
            <label for="email" class="sr-only">Email address</label>
            <input 
              v-model="email" 
              id="email" 
              name="email" 
              type="email" 
              required
              @blur="validateEmail"
              :class="{'border-red-500': emailError}"
              class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
              placeholder="Email address">
            <p v-if="emailError" class="mt-1 text-sm text-red-600">{{ emailError }}</p>
          </div>
          <div>
            <label for="password" class="sr-only">Password</label>
            <input 
              v-model="password" 
              id="password" 
              name="password" 
              type="password" 
              required
              @blur="validatePassword"
              :class="{'border-red-500': passwordError}"
              class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
              placeholder="Password">
            <p v-if="passwordError" class="mt-1 text-sm text-red-600">{{ passwordError }}</p>
          </div>
        </div>
        <div>
          <button 
            type="submit" 
            :disabled="authStore.loading || !isFormValid"
            class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none disabled:opacity-50 disabled:cursor-not-allowed">
            {{ authStore.loading ? 'Signing in...' : 'Sign in' }}
          </button>
        </div>
        <div class="text-center">
          <NuxtLink to="/register" class="text-indigo-600 hover:text-indigo-500">
            Don't have an account? Register
          </NuxtLink>
        </div>
      </form>
    </div>
  </div>
</template>

<script setup lang="ts">
const authStore = useAuthStore()
const router = useRouter()

const email = ref('')
const password = ref('')
const error = ref('')
const emailError = ref('')
const passwordError = ref('')

const isFormValid = computed(() => {
  return email.value.length > 0 && 
         password.value.length > 0 && 
         !emailError.value && 
         !passwordError.value
})

function validateEmail() {
  emailError.value = ''
  if (!email.value) {
    emailError.value = 'Email is required'
    return false
  }
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
  if (!emailRegex.test(email.value)) {
    emailError.value = 'Please enter a valid email address'
    return false
  }
  return true
}

function validatePassword() {
  passwordError.value = ''
  if (!password.value) {
    passwordError.value = 'Password is required'
    return false
  }
  if (password.value.length < 6) {
    passwordError.value = 'Password must be at least 6 characters'
    return false
  }
  return true
}

async function handleLogin() {
  error.value = ''
  emailError.value = ''
  passwordError.value = ''
  
  const isEmailValid = validateEmail()
  const isPasswordValid = validatePassword()
  
  if (!isEmailValid || !isPasswordValid) {
    return
  }
  
  const result = await authStore.login({ email: email.value, password: password.value })
  if (result.success) {
    await authStore.fetchUser()
    router.push('/dashboard')
  } else {
    error.value = result.error || 'Login failed'
  }
}
</script>
